### PR TITLE
Update chat_polish.txt

### PR DESCRIPTION
**Pull request by GitesHubisz**
Hello. I just made a translation of this hud to polish. I hope everything is ok. If not, please correct me. Thanks in advance.

### CODE REVIEW

**Comment by GitesHubisz** [comment]
Is it just me, or did I not make any changes to the fork. Sry, it is first time I have made a Pull Req.

**Comment by rbjaxter** [comment]
Thanks for translating this! I'll take a look later today.

No need to apologize, Git can be pretty confusing. I still don't fully understand it myself... these `chat_` files are treated as binary files by Github, which basically means you won't actually be able to see what changes here in the pull request. I think this has to do with the encoding required for the chat files to work.

I clicked on the "Files changed" tab at the top and then did this to see your version of the file, which appears to reflect the changes you made:
chrome_OAYLP6ORp7

**Comment by rbjaxter** [comment]
It looks like the encoding may need to be changed to match the rest (I usually keep all of the encodings in UTF16LE instead of UTF8). You can also remove this on line 8:         `// English Translations, by: Whisker`

If you'd like to commit those changes feel free, otherwise I can do it on my end :D

**Comment by GitesHubisz** [comment]
I have nothing against it. It would be even better that you will edit my file, rather by myself.

**Comment by rbjaxter** [comment]
Awesome, will do. I will be sure to credit you in the translations as well. dziękuję!

**Comment by GitesHubisz** [comment]
Nie ma za co. :)

**Comment by rbjaxter** [comment]
Random question @GitesHubisz-- if you wanted to use your own Polish translations within budhud, how would you normally go about setting it? Do you have to change the name of `chat_polish` to `chat_english`, or does it automatically detect based on the language Steam or TF2 is set to?

I've always assumed people would have to actually manually change the name/etc, but I haven't checked it myself

**Comment by GitesHubisz** [comment]
Sry if I don't understand correctly, but the answer is that i set it up manually. Steam nor tf2 won't change your huds language (well besides class, items names and etc.)  When I tried to make a translation, i open the English language of your's hud or i use default hud in polish and I was looking at gameplay or menu where and what things are and I just translate it. Currently i changed to polish via updated script.

I hope that explains all, if not, please reply.

@rbjaxter

**Comment by rbjaxter** [comment]
Ahh okay, that does make sense. Thanks for clarifying! :D

**Comment by GitesHubisz** [comment]
np

**Pull request merged**
