### PR TITLE
Update chat_russian.txt

### PR DESCRIPTION
**Pull request by DrPeeper228**

### CODE REVIEW

**Comment by rbjaxter** [comment]
If this is just for #448, I actually already have a commit made for it. I just haven't committed it yet to the branch. If this corrects other labels within that file, though, I can double-check it.

**Comment by DrPeeper228** [comment]
> If this is just for #448, I actually already have a commit made for it. I just haven't committed it yet to the branch. If this corrects other labels within that file, though, I can double-check it.

I seen another bad piece of transition, but i don't remember where it is

**Review by rbjaxter — CHANGES_REQUESTED** [review]
It appears that `"bh_Trading"` was the only entry that changed (relative to what I currently have). If you could change `Обмен` to `ОБМЕН` (just to match the capitalization of everything else), I'll approve the PR 👍

**Comment by DrPeeper228** [comment]
> It appears that `"bh_Trading"` was the only entry that changed (relative to what I currently have). If you could change `Обмен` to `ОБМЕН` (just to match the capitalization of everything else), I'll approve the PR 👍

it is capitalized

**Comment by rbjaxter** [comment]
oh oops lmao, looks good then :D

**Review by rbjaxter — APPROVED** [review]

**Pull request merged**
