### PR TITLE
Added Ukrainian translation as of 19.10.2024

### PR DESCRIPTION
**Pull request by kadabusha**
Hello.
I wanted to add the Ukrainian translation, however the only file I found to be translated was resource/chat_ukrainian.txt
Did my best in making that compatible with existing TF2 Ukrainian translation and kept original encoding.
Please review the changes and let me know if the translation is required in any other place.

TIA

### CODE REVIEW

**Comment by rbjaxter** [comment]
This looks good to me! I'll verify the encoding after I accept the PR.

The only thing I would change is this bit (I can't reference the code directly because this is a binary file):
```
        ////////////////////////////////////////////////////////////////////////////////////////////////////
        // English Translations, by: Whisker
        ////////////////////////////////////////////////////////////////////////////////////////////////////
```

If you could just change it to `Ukrainian Translations, by: <whichever name you want to be credited by>` that'd be perfect

**Comment by rbjaxter** [comment]
I need to make some adjustments, so I will merge this and adjust the title above. I will use your Github name, but let me know if you'd like to be credited with a different name. Thank you for translating!

**Comment by kadabusha** [comment]
Hi @rbjaxter - thanks for checking this!
Title kadabusha is fine - the translation is just a few dozens of lines, should not be of a big issue to adjust further.
If there is some rss or whatever to get notification when new lines are to be translated, I'd like to subscribe to that and keep maintaining the said translation.
Thanks!

**Comment by rbjaxter** [comment]
That's a good question...I'm not sure if there's currently a great way to notify people who have done translations of changes. I try to do it very minimally because there are so many different translation files affected. I'm not sure if you're in the Discord, but if I ever had a lot of translation changes needed I would probably mention it there.

**Pull request merged**
