### PR TITLE
Update chi translation

### PR DESCRIPTION
**Pull request by HotoCocoaco**

### CODE REVIEW

**Comment by rbjaxter** [comment]
This all looks good to me from what I can tell, thank you @HotoCocoaco!

**Comment by rbjaxter** [comment]
Out of curiosity, why did you add the spaces before and after here? Does it make it appear more legibly/easily? 
image

**Comment by HotoCocoaco** [comment]
> 

There is a strange bug. If you don't add an English character / space at the beginning of the sentence, the whole sentence will not be displayed in HUD.

**Comment by rbjaxter** [comment]
Oh, that is strange. And that is just for those hovering tooltips?

**Comment by HotoCocoaco** [comment]
As far as I can tell yes. Probably it can't read it in the start for some reasons.

**Comment by rbjaxter** [comment]
Thanks for pointing that out. Just for consistency I adjusted all of the other chat files to match.

Out of curiosity, what does it take for you to get the chinese chat file to work for you? Do you need to do anything, or do you have to replace the `chat_english` file with the chinese version to get it to appear?

**Comment by HotoCocoaco** [comment]
> Thanks for pointing that out. Just for consistency I adjusted all of the other chat files to match.
> 
> Out of curiosity, what does it take for you to get the chinese chat file to work for you? Do you need to do anything, or do you have to replace the `chat_english` file with the chinese version to get it to appear?

Just edit the chat_schinese and everything is good to go. As long as your game language is correct.

**Pull request merged**
