### PR TITLE
MVM & Arena fixes

### PR DESCRIPTION
**Pull request by Kruphixx**
Before:

After:

### CODE REVIEW

**Comment by Kruphixx** [comment]
Also fixed server time overlapping arena player count.

Before:


After:

**Comment by rbjaxter** [comment]
Mostly looks good, though I wouldn't want to move `ReinforcementsLabel`, because it's meant to slot into this position when the scoreboard's open:
image

**Comment by Kruphixx** [comment]
I can move it back but then it will continue overlapping, though maybe something else can be done in the future

**Comment by rbjaxter** [comment]
yeah tbh I may just remove that respawn note in chat_english if I can, not sure it's really necessary. the rest seems good though :)

**Pull request merged**
