### PR TITLE
Improvements to Match Summary

### PR DESCRIPTION
**Pull request by qkeitoe**

### CODE REVIEW

**Comment by rbjaxter** [comment]
Thanks for making the PR, I'll check it out this weekend (hopefully)

**Comment by qkeitoe** [comment]
I've also noticed the extra text `[unknown]` caused by `bh_descline2shadow` on match summary screen. I'll push the fix a bit later today.

(I made it green for better visibility)
image

**Comment by qkeitoe** [comment]
Now I believe it looks the way it should:
image

Funny fact, `desc2` means different things in Main Menu and in Match Summary:

Main Menu:
image

Match Summary:
image

**Review by rbjaxter — APPROVED** [review]

**Comment by rbjaxter** [comment]
ty for the PR!

**Pull request merged**
