### PR TITLE
re-encode chat files as UTF-8

### PR DESCRIPTION
**Pull request by sheybey**
Encode all chat files as UTF-8 instead of UTF-16. This should prevent issues with encoding detection and it has the nice side benefit of reducing the size of most of the files by nearly 50%.

I actually don't know off the top of my head whether the source engine cares or not and I don't have TF2 installed to test. However, this way the files are consistent with the rest of the hud which we already know works encoded as UTF-8.

### CODE REVIEW

**Comment by sheybey** [comment]
NB: github will always show these files as binary because of the non-printable control characters they contain, which the source engine uses to control text color in the chat box. Would be nice if VDF had escape sequences for arbitrary bytes. Oh well.

**Comment by rbjaxter** [comment]
Just because I don't have too much familiarity when it comes to encoding-- is there anything I should do on my end to ensure this sticks when I'm working on the hud locally?

I suppose short of not changing the encoding of the files back myself, I imagine there aren't any other ways they could unintentionally be reverted to UTF-16, but I figured it couldn't hurt to ask since I know little in this area.

**Comment by rbjaxter** [comment]
ty for spotting this btw :D

**Comment by rbjaxter** [comment]
ah wait a sec, right after committing I remembered these chat files need to be encoded in Little Endian or they won't work (as far as I remember). let me double-check

**Comment by rbjaxter** [comment]
yeah, setting encoding to UTF-8 breaks the language tokens unfortunately

**Pull request merged**
